Repository OriginProtocol/origin, pull requests merged in 2018-10, with the labels that each got.

#645 Implement a simple way to feature/hide listings
  src/actions/Listing.js
  src/components/app.js
  src/components/badges.js
  src/components/listing-card.js
  src/components/listing-detail.js
  src/components/listings-grid.js
  src/css/app.css
  src/reducers/Listings.js
  translations/all-messages.json
  translations/messages/src/components/badges.json
  translations/messages/src/components/listing-card.json
Labels: feature, p0

#654 Fix for hidden/featured listings
  src/actions/Listing.js
Labels: bug

#709 Featured Badge fixes
  src/components/listing-card.js
  src/components/listing-detail.js
  src/components/listings-grid.js
Labels: bug, dapp

#721 Another pagination fix
  src/components/listings-grid.js
  src/components/web3-provider.js
Labels: bug

#816 fix the command that starts origin-js process
  docker-compose.yml
Labels: bug, origin.js

#844 Sparrow dom/es index migration
  development/scripts/create-es-index.sh
  development/scripts/elasticsearch/migration-tool.js
Labels: devops, feature, search

#848 fix bug that crashed ipfs proxy when 404 status should be reported
  ipfs-proxy/src/index.js
Labels: bug

#851 Added tooltips for important elements often truncated
  origin-dapp/src/components/arbitration.js
  origin-dapp/src/components/listing-card.js
  origin-dapp/src/components/my-listing-card.js
  origin-dapp/src/components/my-purchase-card.js
  origin-dapp/src/components/notification.js
  origin-dapp/src/components/purchase-detail.js
  origin-dapp/src/components/review.js
  origin-dapp/translations/all-messages.json
  origin-dapp/translations/messages/src/components/listing-detail.json
Labels: ui/ux
