Repository OriginProtocol/origin, pull requests merged in 2020-05, with the labels that each got.

#4453 Dshop: adds /affiliate/products endpoint
  dapps/shop/backend/package.json
  dapps/shop/backend/routes/affiliate.js
Labels: enhancement

#4455 Dshop GCP VM image builder
  dapps/shop/backend/scripts/gcp/marketplace/README.md
  dapps/shop/backend/scripts/gcp/marketplace/build.sh
  dapps/shop/backend/scripts/gcp/marketplace/startup_script.sh
Labels: devops, enhancement

#4467 Start of a place to dump dshop notes and diagrams.
  dapps/shop/docs/assets/dshop-flow.afdesign
  dapps/shop/docs/assets/dshop-flow.png
  dapps/shop/docs/assets/dshop-offer.afdesign
  dapps/shop/docs/assets/dshop-offer.png
  dapps/shop/docs/index.md
  dapps/shop/docs/order.md
Labels: dshop

#4465 Queue for dshop backend processes
  dapps/shop/README.md
  dapps/shop/backend/README.md
  dapps/shop/backend/app.js
  dapps/shop/backend/docs/README.md
  dapps/shop/backend/package.json
  dapps/shop/backend/queues/fallbackQueue.js
  dapps/shop/backend/queues/index.js
  dapps/shop/backend/queues/makeOfferProcessor.js
  dapps/shop/backend/queues/queues.js
  dapps/shop/backend/queues/ui.js
  dapps/shop/backend/routes/_makeOffer.js
  dapps/shop/backend/utils/const.js
  yarn.lock
Labels: dshop

#4473 Upgrades ipfs to v0.5.1 and run migrations
  devops/kubernetes/charts/origin/templates/ipfs.statefulset.yaml
  devops/kubernetes/charts/origin/values.yaml
Labels: devops, ipfs
